import { Toaster } from "sonner";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Cairo, Inter } from "next/font/google";

import "./globals.css";
import { Providers } from "./providers/providers";
import FacebookSDK from "./providers/FacebookProvider";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-cairo",
});

export const metadata: Metadata = {
  title: "motqin",
  description: "Generated by MONO",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("font-sans", inter.variable)}
    >
      <head>
        <FacebookSDK />
      </head>
      <body
        className={`${geistSans.variable} ${cairo.className} antialiased`}
        suppressHydrationWarning
      >
        <main>
          <Providers>
            {children}
            <Toaster
              position="top-center"
              richColors
              expand
              dir="rtl"
              closeButton
              toastOptions={{
                classNames: {
                  toast:
                    "rounded-2xl border border-zinc-200 dark:border-zinc-800 shadow-xl max-w-[50vw]",
                  title: "font-semibold text-[15px]",
                  description: "text-sm",
                  success: "bg-green-50 dark:bg-green-950",
                  error: "bg-red-50 dark:bg-red-950",
                  warning: "bg-yellow-50 dark:bg-yellow-950",
                  info: "bg-blue-50 dark:bg-blue-950",
                },
              }}
            />
          </Providers>
        </main>
      </body>
    </html>
  );
}
