import { Toaster } from "sonner";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Cairo } from "next/font/google";

import "./globals.css";
import { Providers } from "./providers/providers";
import Script from "next/script";
import FacebookSDK from "./providers/FacebookProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-cairo",
});

export const metadata: Metadata = {
  title: "motqin",
  description: "Generated by MONO",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <FacebookSDK />
      </head>
      <body className={`${geistSans.variable} ${cairo.className} antialiased`}>
        <main>
          <Providers>
            {children}
            <Toaster position="top-center" richColors closeButton />
          </Providers>
        </main>
      </body>
    </html>
  );
}
